# Generated by Django 5.0.2 on 2024-03-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_urlconversion_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlconversion',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='urlconversion',
            name='user_agent',
        ),
    ]
